package com.example.entity2;

import java.io.Serializable;
import java.sql.*;
import javax.annotation.Nonnull;
import jakarta.persistence.*;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Entity(name = "com.example.entity2.BlogArticleTag")
@Table(name = "article_tag")
public class BlogArticleTag implements Serializable {

  public Integer getId() { return this.id; }

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private int id;
  /**
   * database comment for article_id
   * The field is non-null value
   */
  @Column(name = "\"article_id\"", nullable = false)
  private int articleId;
  /**
   * database comment for blog_id
   * The field is non-null value
   */
  @Column(name = "\"tag_id\"", nullable = false)
  private int tagId;
  @Nonnull
  @Column(name = "\"created_at\"", nullable = false)
  private Timestamp createdAt;

  public void setId(int id) {
    this.id = id;
  }

  public int getArticleId() {
    return articleId;
  }

  public void setArticleId(int articleId) {
    this.articleId = articleId;
  }

  public int getTagId() {
    return tagId;
  }

  public void setTagId(int tagId) {
    this.tagId = tagId;
  }

  @Nonnull
  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@Nonnull Timestamp createdAt) {
    this.createdAt = createdAt;
  }
}